// Extruded 3D text from the bundled OFL fonts (typeface JSON generated by
// scripts/make-typeface.mjs). Geometries are cached and centered on the origin.
//
// TextGeometry has two material groups: 0 = front/back faces, 1 = sides/bevel,
// so `new Mesh(geo, [faceMaterial, sideMaterial])` gives e.g. neon faces + chrome edges.

import * as THREE from 'three';
import { FontLoader, type Font } from 'three/examples/jsm/loaders/FontLoader.js';
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry.js';
import orbitron from '../assets/fonts/orbitron-black.typeface.json';
import delaKanji from '../assets/fonts/dela-kanji.typeface.json';
import delaLatin from '../assets/fonts/dela-latin.typeface.json';

export type FontName = 'display' | 'heavy' | 'kanji';

const loader = new FontLoader();
const FONTS: Record<FontName, Font> = {
  display: loader.parse(orbitron as never), // Orbitron Black: 10 J Q K A, WILD, BONUS, logo, multipliers
  heavy: loader.parse(delaLatin as never), // Dela Gothic One latin: chunky alternative
  kanji: loader.parse(delaKanji as never), // 雷 神 電 力 鬼 風 嵐 天 怒 王
};

export interface TextOptions {
  font?: FontName;
  /** Cap height-ish size in world units. */
  size?: number;
  depth?: number;
  bevel?: number;
  bevelSegments?: number;
  curveSegments?: number;
  /** Horizontal alignment of the bounding box around x = 0. */
  align?: 'center' | 'left' | 'right';
}

const cache = new Map<string, THREE.BufferGeometry>();

export function textGeometry(text: string, o: TextOptions = {}): THREE.BufferGeometry {
  const opts = { font: 'display' as FontName, size: 1, depth: 0.2, bevel: 0.03, bevelSegments: 3, curveSegments: 6, align: 'center' as const, ...o };
  const key = JSON.stringify([text, opts]);
  let g = cache.get(key);
  if (g) return g;
  g = new TextGeometry(text, {
    font: FONTS[opts.font],
    size: opts.size,
    depth: opts.depth,
    curveSegments: opts.curveSegments,
    bevelEnabled: opts.bevel > 0,
    bevelThickness: opts.bevel,
    bevelSize: opts.bevel * 0.8,
    bevelSegments: opts.bevelSegments,
  });
  g.computeBoundingBox();
  const bb = g.boundingBox!;
  const cx = opts.align === 'left' ? bb.min.x : opts.align === 'right' ? bb.max.x : (bb.min.x + bb.max.x) / 2;
  g.translate(-cx, -(bb.min.y + bb.max.y) / 2, -(bb.min.z + bb.max.z) / 2);
  g.computeVertexNormals();
  cache.set(key, g);
  return g;
}

/** Convenience: text mesh with face + side materials. */
export function textMesh(text: string, face: THREE.Material, side: THREE.Material = face, o: TextOptions = {}): THREE.Mesh {
  return new THREE.Mesh(textGeometry(text, o), [face, side]);
}

/** Size of a cached text geometry (after centering). */
export function textSize(geo: THREE.BufferGeometry): THREE.Vector3 {
  geo.computeBoundingBox();
  return geo.boundingBox!.getSize(new THREE.Vector3());
}
